spring.application.name=neuroarena-backend

game.max-players=10
game.questions-per-battle=10
game.question-time-limit=30

groq.api.key=${GROQ_API_KEY}

# ===============================
# H2 DATABASE
# ===============================
spring.datasource.url=jdbc:h2:mem:neuroarena;MODE=MYSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 CONSOLE (UI)
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console